# Generated by Django 2.0.6 on 2018-06-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='手机号')),
                ('address', models.CharField(help_text='例如:2栋2单元401', max_length=20, verbose_name='地址')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '使用者详情',
                'verbose_name': '使用者详情',
            },
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='维修师傅姓名', max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, default='', max_length=32, verbose_name='订单号')),
                ('user_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='用户报修描述')),
                ('repair_address', models.CharField(help_text='默认拉去用户的地址,如果没有就需要用户填写', max_length=30, verbose_name='用户报修地址')),
                ('order_status', models.IntegerField(choices=[(10, '等待分配'), (20, '等待接单'), (30, '等待维修'), (40, '加急'), (50, '维修中'), (60, '维修完成'), (70, '评价'), (80, '取消')], default=10, verbose_name='订单状态')),
                ('cancel_remark', models.CharField(blank=True, default='', max_length=200, verbose_name='取消备注')),
                ('user_grade', models.IntegerField(blank=True, choices=[(0, '一星'), (1, '两星'), (2, '三星'), (3, '四星'), (4, '五星')], help_text='用户评价等级', verbose_name='用户评分')),
                ('user_evaluate', models.CharField(max_length=200, verbose_name='用户评价')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.CustomerProfile')),
            ],
            options={
                'verbose_name_plural': '报修订单',
                'verbose_name': '报修订单',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='物管名称', max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='手机号')),
                ('tel', models.CharField(default='', max_length=20, verbose_name='座机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '物管名称',
                'verbose_name': '物管名称',
            },
        ),
        migrations.CreateModel(
            name='WxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='维修类型')),
                ('type_desc', models.CharField(max_length=300, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '维修类型',
                'verbose_name': '维修类型',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='wx_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WxType'),
        ),
        migrations.AddField(
            model_name='order',
            name='wx_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Maintainer'),
        ),
    ]
