# Generated by Django 2.0.6 on 2018-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='wx_type',
            field=models.CharField(default='', max_length=200, verbose_name='维修类型'),
        ),
    ]
