# Generated by Django 2.0.6 on 2018-07-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180717_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_remark',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='取消备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_evaluate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='用户评价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_grade',
            field=models.IntegerField(blank=True, choices=[(0, '一星'), (1, '两星'), (2, '三星'), (3, '四星'), (4, '五星')], help_text='用户评价等级', null=True, verbose_name='用户评分'),
        ),
    ]
